---
- name: "Create backend app dir"
  file:
    path: ~/backend-app
    state: directory

- name: "untar build of frontend files"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app


- name: "install serve dependency"
  shell: |
    npm install -g serve

- name: "execute node app with npm"
  shell: |
    cd ~/backend-app
    serve -s build

  register: execute_node_output

- name: "print message"
  debug:
    msg: "{{ execute_node_output.stdout_lines }}"
