---
- name: "Create backend app dir"
  file:
    path: ~/backend-app
    state: directory

- name: "untar build of frontend files"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app


# - name: "install node dependencies"
#   shell: |
#     cd ~/backend-app
#     npm i

- name: "execute node app with npm"
  shell: |
    cd ~/backend-app
    npm install -g serve
    npm serve

  register: execute_node_output

- name: "print message"
  debug:
    msg: "{{ execute_node_output.stdout_lines }}"
