---
- name: "Create backend app dir"
  file:
    path: /home/ubuntu/backend-app
    state: directory



# - name: "Create backend app dir"
#   shell: |
#     mkdir ~/backend-app


- name: "untar build of frontend files"
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/backend-app
    

- name: "install serve dependency"
  shell: |
    npm install -g serve


- name: "ls"
  shell: |
    ls

- name: "execute node app with npm"
  shell: |
    cd /home/ubuntu/backend-app
    serve -s build

  register: execute_node_output

- name: "print message"
  debug:
    msg: "{{ execute_node_output.stdout_lines }}"
