Description: >
  AMRs-in-Warehouse-Systems webapplication stack.

Parameters:
  ID:
    Description: Unique identifier.
    Type: String
      

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
          
      SecurityGroupIds:
        - sg-080689485792a93d7
          
      KeyName: AMRs-in-Warehouse-Systems
      # If this ami id is not available for you, you can find another (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/finding-an-ami.html)
      # Ubuntu 18 or higher works fine
      ImageId: ami-0261755bbcb8c4a84
      Tags:
        - Key: Name
          Value: !Sub webapplications-${ID}
        - Key: Project
          Value: AMRs-in-Warehouse-Systems
