version: 2.1
     
jobs:
  build-frontend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build-deps]
      - run:
          name: Build front-end
          command: |
            cd dashboard-web-application
            cd client
            npm install
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build-deps

  build-backend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build-deps]
      - run:
          name: Back-end build
          command: |
            cd dashboard-web-application
            cd server
            npm install
            npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build

  scan-frontend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build-deps]
      - run:
          name: frontend-scan
          command: |
            cd dashboard-web-application
            cd client
            npm install
            npm audit fix --force --audit-level=critical
            npm audit --audit-level=critical

  scan-backend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build-deps]
      - run:
          name: backend-scan
          command: |
            cd dashboard-web-application
            cd server
            npm install
            npm audit fix --force --audit-level=critical
            npm audit fix --force --audit-level=critical
            npm audit --audit-level=critical
    
workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
      - scan-backend:
          requires: [build-backend]
      - scan-frontend:
          requires: [build-frontend]